// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Kevin-Lab777/sub2api/ent/apikey"
	"github.com/Kevin-Lab777/sub2api/ent/group"
	"github.com/Kevin-Lab777/sub2api/ent/predicate"
	"github.com/Kevin-Lab777/sub2api/ent/usagelog"
	"github.com/Kevin-Lab777/sub2api/ent/user"
)

// APIKeyUpdate is the builder for updating APIKey entities.
type APIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyMutation
}

// Where appends a list predicates to the APIKeyUpdate builder.
func (_u *APIKeyUpdate) Where(ps ...predicate.APIKey) *APIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyUpdate) SetUpdatedAt(v time.Time) *APIKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIKeyUpdate) SetDeletedAt(v time.Time) *APIKeyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableDeletedAt(v *time.Time) *APIKeyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *APIKeyUpdate) ClearDeletedAt() *APIKeyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *APIKeyUpdate) SetUserID(v int64) *APIKeyUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableUserID(v *int64) *APIKeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *APIKeyUpdate) SetKey(v string) *APIKeyUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableKey(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *APIKeyUpdate) SetName(v string) *APIKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableName(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyUpdate) SetGroupID(v int64) *APIKeyUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableGroupID(v *int64) *APIKeyUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *APIKeyUpdate) ClearGroupID() *APIKeyUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *APIKeyUpdate) SetStatus(v string) *APIKeyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableStatus(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIPWhitelist sets the "ip_whitelist" field.
func (_u *APIKeyUpdate) SetIPWhitelist(v []string) *APIKeyUpdate {
	_u.mutation.SetIPWhitelist(v)
	return _u
}

// AppendIPWhitelist appends value to the "ip_whitelist" field.
func (_u *APIKeyUpdate) AppendIPWhitelist(v []string) *APIKeyUpdate {
	_u.mutation.AppendIPWhitelist(v)
	return _u
}

// ClearIPWhitelist clears the value of the "ip_whitelist" field.
func (_u *APIKeyUpdate) ClearIPWhitelist() *APIKeyUpdate {
	_u.mutation.ClearIPWhitelist()
	return _u
}

// SetIPBlacklist sets the "ip_blacklist" field.
func (_u *APIKeyUpdate) SetIPBlacklist(v []string) *APIKeyUpdate {
	_u.mutation.SetIPBlacklist(v)
	return _u
}

// AppendIPBlacklist appends value to the "ip_blacklist" field.
func (_u *APIKeyUpdate) AppendIPBlacklist(v []string) *APIKeyUpdate {
	_u.mutation.AppendIPBlacklist(v)
	return _u
}

// ClearIPBlacklist clears the value of the "ip_blacklist" field.
func (_u *APIKeyUpdate) ClearIPBlacklist() *APIKeyUpdate {
	_u.mutation.ClearIPBlacklist()
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *APIKeyUpdate) SetDailyLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableDailyLimitUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *APIKeyUpdate) AddDailyLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *APIKeyUpdate) ClearDailyLimitUsd() *APIKeyUpdate {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *APIKeyUpdate) SetWeeklyLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableWeeklyLimitUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *APIKeyUpdate) AddWeeklyLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *APIKeyUpdate) ClearWeeklyLimitUsd() *APIKeyUpdate {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *APIKeyUpdate) SetMonthlyLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableMonthlyLimitUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *APIKeyUpdate) AddMonthlyLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *APIKeyUpdate) ClearMonthlyLimitUsd() *APIKeyUpdate {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (_u *APIKeyUpdate) SetTotalLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetTotalLimitUsd()
	_u.mutation.SetTotalLimitUsd(v)
	return _u
}

// SetNillableTotalLimitUsd sets the "total_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableTotalLimitUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetTotalLimitUsd(*v)
	}
	return _u
}

// AddTotalLimitUsd adds value to the "total_limit_usd" field.
func (_u *APIKeyUpdate) AddTotalLimitUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddTotalLimitUsd(v)
	return _u
}

// ClearTotalLimitUsd clears the value of the "total_limit_usd" field.
func (_u *APIKeyUpdate) ClearTotalLimitUsd() *APIKeyUpdate {
	_u.mutation.ClearTotalLimitUsd()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *APIKeyUpdate) SetDailyUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableDailyUsageUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *APIKeyUpdate) AddDailyUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *APIKeyUpdate) SetWeeklyUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableWeeklyUsageUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *APIKeyUpdate) AddWeeklyUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *APIKeyUpdate) SetMonthlyUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableMonthlyUsageUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *APIKeyUpdate) AddMonthlyUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetTotalUsageUsd sets the "total_usage_usd" field.
func (_u *APIKeyUpdate) SetTotalUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.ResetTotalUsageUsd()
	_u.mutation.SetTotalUsageUsd(v)
	return _u
}

// SetNillableTotalUsageUsd sets the "total_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableTotalUsageUsd(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetTotalUsageUsd(*v)
	}
	return _u
}

// AddTotalUsageUsd adds value to the "total_usage_usd" field.
func (_u *APIKeyUpdate) AddTotalUsageUsd(v float64) *APIKeyUpdate {
	_u.mutation.AddTotalUsageUsd(v)
	return _u
}

// SetUsageResetDaily sets the "usage_reset_daily" field.
func (_u *APIKeyUpdate) SetUsageResetDaily(v time.Time) *APIKeyUpdate {
	_u.mutation.SetUsageResetDaily(v)
	return _u
}

// SetNillableUsageResetDaily sets the "usage_reset_daily" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableUsageResetDaily(v *time.Time) *APIKeyUpdate {
	if v != nil {
		_u.SetUsageResetDaily(*v)
	}
	return _u
}

// ClearUsageResetDaily clears the value of the "usage_reset_daily" field.
func (_u *APIKeyUpdate) ClearUsageResetDaily() *APIKeyUpdate {
	_u.mutation.ClearUsageResetDaily()
	return _u
}

// SetUsageResetWeekly sets the "usage_reset_weekly" field.
func (_u *APIKeyUpdate) SetUsageResetWeekly(v time.Time) *APIKeyUpdate {
	_u.mutation.SetUsageResetWeekly(v)
	return _u
}

// SetNillableUsageResetWeekly sets the "usage_reset_weekly" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableUsageResetWeekly(v *time.Time) *APIKeyUpdate {
	if v != nil {
		_u.SetUsageResetWeekly(*v)
	}
	return _u
}

// ClearUsageResetWeekly clears the value of the "usage_reset_weekly" field.
func (_u *APIKeyUpdate) ClearUsageResetWeekly() *APIKeyUpdate {
	_u.mutation.ClearUsageResetWeekly()
	return _u
}

// SetUsageResetMonthly sets the "usage_reset_monthly" field.
func (_u *APIKeyUpdate) SetUsageResetMonthly(v time.Time) *APIKeyUpdate {
	_u.mutation.SetUsageResetMonthly(v)
	return _u
}

// SetNillableUsageResetMonthly sets the "usage_reset_monthly" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableUsageResetMonthly(v *time.Time) *APIKeyUpdate {
	if v != nil {
		_u.SetUsageResetMonthly(*v)
	}
	return _u
}

// ClearUsageResetMonthly clears the value of the "usage_reset_monthly" field.
func (_u *APIKeyUpdate) ClearUsageResetMonthly() *APIKeyUpdate {
	_u.mutation.ClearUsageResetMonthly()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *APIKeyUpdate) SetQuota(v float64) *APIKeyUpdate {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableQuota(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *APIKeyUpdate) AddQuota(v float64) *APIKeyUpdate {
	_u.mutation.AddQuota(v)
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *APIKeyUpdate) SetQuotaUsed(v float64) *APIKeyUpdate {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableQuotaUsed(v *float64) *APIKeyUpdate {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *APIKeyUpdate) AddQuotaUsed(v float64) *APIKeyUpdate {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *APIKeyUpdate) SetExpiresAt(v time.Time) *APIKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableExpiresAt(v *time.Time) *APIKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *APIKeyUpdate) ClearExpiresAt() *APIKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *APIKeyUpdate) SetUser(v *User) *APIKeyUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyUpdate) SetGroup(v *Group) *APIKeyUpdate {
	return _u.SetGroupID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *APIKeyUpdate) AddUsageLogIDs(ids ...int64) *APIKeyUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *APIKeyUpdate) AddUsageLogs(v ...*UsageLog) *APIKeyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the APIKeyMutation object of the builder.
func (_u *APIKeyUpdate) Mutation() *APIKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *APIKeyUpdate) ClearUser() *APIKeyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyUpdate) ClearGroup() *APIKeyUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *APIKeyUpdate) ClearUsageLogs() *APIKeyUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *APIKeyUpdate) RemoveUsageLogIDs(ids ...int64) *APIKeyUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *APIKeyUpdate) RemoveUsageLogs(v ...*UsageLog) *APIKeyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if apikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := apikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "APIKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := apikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "APIKey.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKey.user"`)
	}
	return nil
}

func (_u *APIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apikey.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPWhitelist(); ok {
		_spec.SetField(apikey.FieldIPWhitelist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPWhitelist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldIPWhitelist, value)
		})
	}
	if _u.mutation.IPWhitelistCleared() {
		_spec.ClearField(apikey.FieldIPWhitelist, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPBlacklist(); ok {
		_spec.SetField(apikey.FieldIPBlacklist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPBlacklist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldIPBlacklist, value)
		})
	}
	if _u.mutation.IPBlacklistCleared() {
		_spec.ClearField(apikey.FieldIPBlacklist, field.TypeJSON)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(apikey.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(apikey.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(apikey.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(apikey.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(apikey.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(apikey.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(apikey.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(apikey.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(apikey.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalLimitUsd(); ok {
		_spec.SetField(apikey.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalLimitUsd(); ok {
		_spec.AddField(apikey.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.TotalLimitUsdCleared() {
		_spec.ClearField(apikey.FieldTotalLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(apikey.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(apikey.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(apikey.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(apikey.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(apikey.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(apikey.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalUsageUsd(); ok {
		_spec.SetField(apikey.FieldTotalUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalUsageUsd(); ok {
		_spec.AddField(apikey.FieldTotalUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsageResetDaily(); ok {
		_spec.SetField(apikey.FieldUsageResetDaily, field.TypeTime, value)
	}
	if _u.mutation.UsageResetDailyCleared() {
		_spec.ClearField(apikey.FieldUsageResetDaily, field.TypeTime)
	}
	if value, ok := _u.mutation.UsageResetWeekly(); ok {
		_spec.SetField(apikey.FieldUsageResetWeekly, field.TypeTime, value)
	}
	if _u.mutation.UsageResetWeeklyCleared() {
		_spec.ClearField(apikey.FieldUsageResetWeekly, field.TypeTime)
	}
	if value, ok := _u.mutation.UsageResetMonthly(); ok {
		_spec.SetField(apikey.FieldUsageResetMonthly, field.TypeTime, value)
	}
	if _u.mutation.UsageResetMonthlyCleared() {
		_spec.ClearField(apikey.FieldUsageResetMonthly, field.TypeTime)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(apikey.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(apikey.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(apikey.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(apikey.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apikey.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.GroupTable,
			Columns: []string{apikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.GroupTable,
			Columns: []string{apikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.UsageLogsTable,
			Columns: []string{apikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.UsageLogsTable,
			Columns: []string{apikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.UsageLogsTable,
			Columns: []string{apikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyUpdateOne is the builder for updating a single APIKey entity.
type APIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyUpdateOne) SetUpdatedAt(v time.Time) *APIKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIKeyUpdateOne) SetDeletedAt(v time.Time) *APIKeyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableDeletedAt(v *time.Time) *APIKeyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *APIKeyUpdateOne) ClearDeletedAt() *APIKeyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *APIKeyUpdateOne) SetUserID(v int64) *APIKeyUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableUserID(v *int64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *APIKeyUpdateOne) SetKey(v string) *APIKeyUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableKey(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *APIKeyUpdateOne) SetName(v string) *APIKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableName(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyUpdateOne) SetGroupID(v int64) *APIKeyUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableGroupID(v *int64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *APIKeyUpdateOne) ClearGroupID() *APIKeyUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *APIKeyUpdateOne) SetStatus(v string) *APIKeyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableStatus(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIPWhitelist sets the "ip_whitelist" field.
func (_u *APIKeyUpdateOne) SetIPWhitelist(v []string) *APIKeyUpdateOne {
	_u.mutation.SetIPWhitelist(v)
	return _u
}

// AppendIPWhitelist appends value to the "ip_whitelist" field.
func (_u *APIKeyUpdateOne) AppendIPWhitelist(v []string) *APIKeyUpdateOne {
	_u.mutation.AppendIPWhitelist(v)
	return _u
}

// ClearIPWhitelist clears the value of the "ip_whitelist" field.
func (_u *APIKeyUpdateOne) ClearIPWhitelist() *APIKeyUpdateOne {
	_u.mutation.ClearIPWhitelist()
	return _u
}

// SetIPBlacklist sets the "ip_blacklist" field.
func (_u *APIKeyUpdateOne) SetIPBlacklist(v []string) *APIKeyUpdateOne {
	_u.mutation.SetIPBlacklist(v)
	return _u
}

// AppendIPBlacklist appends value to the "ip_blacklist" field.
func (_u *APIKeyUpdateOne) AppendIPBlacklist(v []string) *APIKeyUpdateOne {
	_u.mutation.AppendIPBlacklist(v)
	return _u
}

// ClearIPBlacklist clears the value of the "ip_blacklist" field.
func (_u *APIKeyUpdateOne) ClearIPBlacklist() *APIKeyUpdateOne {
	_u.mutation.ClearIPBlacklist()
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *APIKeyUpdateOne) SetDailyLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableDailyLimitUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *APIKeyUpdateOne) AddDailyLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *APIKeyUpdateOne) ClearDailyLimitUsd() *APIKeyUpdateOne {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *APIKeyUpdateOne) SetWeeklyLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableWeeklyLimitUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *APIKeyUpdateOne) AddWeeklyLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *APIKeyUpdateOne) ClearWeeklyLimitUsd() *APIKeyUpdateOne {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *APIKeyUpdateOne) SetMonthlyLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableMonthlyLimitUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *APIKeyUpdateOne) AddMonthlyLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *APIKeyUpdateOne) ClearMonthlyLimitUsd() *APIKeyUpdateOne {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetTotalLimitUsd sets the "total_limit_usd" field.
func (_u *APIKeyUpdateOne) SetTotalLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetTotalLimitUsd()
	_u.mutation.SetTotalLimitUsd(v)
	return _u
}

// SetNillableTotalLimitUsd sets the "total_limit_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableTotalLimitUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetTotalLimitUsd(*v)
	}
	return _u
}

// AddTotalLimitUsd adds value to the "total_limit_usd" field.
func (_u *APIKeyUpdateOne) AddTotalLimitUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddTotalLimitUsd(v)
	return _u
}

// ClearTotalLimitUsd clears the value of the "total_limit_usd" field.
func (_u *APIKeyUpdateOne) ClearTotalLimitUsd() *APIKeyUpdateOne {
	_u.mutation.ClearTotalLimitUsd()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *APIKeyUpdateOne) SetDailyUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableDailyUsageUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *APIKeyUpdateOne) AddDailyUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *APIKeyUpdateOne) SetWeeklyUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableWeeklyUsageUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *APIKeyUpdateOne) AddWeeklyUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *APIKeyUpdateOne) SetMonthlyUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *APIKeyUpdateOne) AddMonthlyUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetTotalUsageUsd sets the "total_usage_usd" field.
func (_u *APIKeyUpdateOne) SetTotalUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetTotalUsageUsd()
	_u.mutation.SetTotalUsageUsd(v)
	return _u
}

// SetNillableTotalUsageUsd sets the "total_usage_usd" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableTotalUsageUsd(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetTotalUsageUsd(*v)
	}
	return _u
}

// AddTotalUsageUsd adds value to the "total_usage_usd" field.
func (_u *APIKeyUpdateOne) AddTotalUsageUsd(v float64) *APIKeyUpdateOne {
	_u.mutation.AddTotalUsageUsd(v)
	return _u
}

// SetUsageResetDaily sets the "usage_reset_daily" field.
func (_u *APIKeyUpdateOne) SetUsageResetDaily(v time.Time) *APIKeyUpdateOne {
	_u.mutation.SetUsageResetDaily(v)
	return _u
}

// SetNillableUsageResetDaily sets the "usage_reset_daily" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableUsageResetDaily(v *time.Time) *APIKeyUpdateOne {
	if v != nil {
		_u.SetUsageResetDaily(*v)
	}
	return _u
}

// ClearUsageResetDaily clears the value of the "usage_reset_daily" field.
func (_u *APIKeyUpdateOne) ClearUsageResetDaily() *APIKeyUpdateOne {
	_u.mutation.ClearUsageResetDaily()
	return _u
}

// SetUsageResetWeekly sets the "usage_reset_weekly" field.
func (_u *APIKeyUpdateOne) SetUsageResetWeekly(v time.Time) *APIKeyUpdateOne {
	_u.mutation.SetUsageResetWeekly(v)
	return _u
}

// SetNillableUsageResetWeekly sets the "usage_reset_weekly" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableUsageResetWeekly(v *time.Time) *APIKeyUpdateOne {
	if v != nil {
		_u.SetUsageResetWeekly(*v)
	}
	return _u
}

// ClearUsageResetWeekly clears the value of the "usage_reset_weekly" field.
func (_u *APIKeyUpdateOne) ClearUsageResetWeekly() *APIKeyUpdateOne {
	_u.mutation.ClearUsageResetWeekly()
	return _u
}

// SetUsageResetMonthly sets the "usage_reset_monthly" field.
func (_u *APIKeyUpdateOne) SetUsageResetMonthly(v time.Time) *APIKeyUpdateOne {
	_u.mutation.SetUsageResetMonthly(v)
	return _u
}

// SetNillableUsageResetMonthly sets the "usage_reset_monthly" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableUsageResetMonthly(v *time.Time) *APIKeyUpdateOne {
	if v != nil {
		_u.SetUsageResetMonthly(*v)
	}
	return _u
}

// ClearUsageResetMonthly clears the value of the "usage_reset_monthly" field.
func (_u *APIKeyUpdateOne) ClearUsageResetMonthly() *APIKeyUpdateOne {
	_u.mutation.ClearUsageResetMonthly()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *APIKeyUpdateOne) SetQuota(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableQuota(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *APIKeyUpdateOne) AddQuota(v float64) *APIKeyUpdateOne {
	_u.mutation.AddQuota(v)
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *APIKeyUpdateOne) SetQuotaUsed(v float64) *APIKeyUpdateOne {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableQuotaUsed(v *float64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *APIKeyUpdateOne) AddQuotaUsed(v float64) *APIKeyUpdateOne {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *APIKeyUpdateOne) SetExpiresAt(v time.Time) *APIKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *APIKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *APIKeyUpdateOne) ClearExpiresAt() *APIKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *APIKeyUpdateOne) SetUser(v *User) *APIKeyUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyUpdateOne) SetGroup(v *Group) *APIKeyUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *APIKeyUpdateOne) AddUsageLogIDs(ids ...int64) *APIKeyUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *APIKeyUpdateOne) AddUsageLogs(v ...*UsageLog) *APIKeyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the APIKeyMutation object of the builder.
func (_u *APIKeyUpdateOne) Mutation() *APIKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *APIKeyUpdateOne) ClearUser() *APIKeyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyUpdateOne) ClearGroup() *APIKeyUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *APIKeyUpdateOne) ClearUsageLogs() *APIKeyUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *APIKeyUpdateOne) RemoveUsageLogIDs(ids ...int64) *APIKeyUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *APIKeyUpdateOne) RemoveUsageLogs(v ...*UsageLog) *APIKeyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the APIKeyUpdate builder.
func (_u *APIKeyUpdateOne) Where(ps ...predicate.APIKey) *APIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyUpdateOne) Select(field string, fields ...string) *APIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKey entity.
func (_u *APIKeyUpdateOne) Save(ctx context.Context) (*APIKey, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyUpdateOne) SaveX(ctx context.Context) *APIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if apikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := apikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "APIKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "APIKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := apikey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "APIKey.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKey.user"`)
	}
	return nil
}

func (_u *APIKeyUpdateOne) sqlSave(ctx context.Context) (_node *APIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apikey.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPWhitelist(); ok {
		_spec.SetField(apikey.FieldIPWhitelist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPWhitelist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldIPWhitelist, value)
		})
	}
	if _u.mutation.IPWhitelistCleared() {
		_spec.ClearField(apikey.FieldIPWhitelist, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPBlacklist(); ok {
		_spec.SetField(apikey.FieldIPBlacklist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPBlacklist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldIPBlacklist, value)
		})
	}
	if _u.mutation.IPBlacklistCleared() {
		_spec.ClearField(apikey.FieldIPBlacklist, field.TypeJSON)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(apikey.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(apikey.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(apikey.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(apikey.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(apikey.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(apikey.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(apikey.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(apikey.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(apikey.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalLimitUsd(); ok {
		_spec.SetField(apikey.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalLimitUsd(); ok {
		_spec.AddField(apikey.FieldTotalLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.TotalLimitUsdCleared() {
		_spec.ClearField(apikey.FieldTotalLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(apikey.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(apikey.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(apikey.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(apikey.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(apikey.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(apikey.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalUsageUsd(); ok {
		_spec.SetField(apikey.FieldTotalUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalUsageUsd(); ok {
		_spec.AddField(apikey.FieldTotalUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsageResetDaily(); ok {
		_spec.SetField(apikey.FieldUsageResetDaily, field.TypeTime, value)
	}
	if _u.mutation.UsageResetDailyCleared() {
		_spec.ClearField(apikey.FieldUsageResetDaily, field.TypeTime)
	}
	if value, ok := _u.mutation.UsageResetWeekly(); ok {
		_spec.SetField(apikey.FieldUsageResetWeekly, field.TypeTime, value)
	}
	if _u.mutation.UsageResetWeeklyCleared() {
		_spec.ClearField(apikey.FieldUsageResetWeekly, field.TypeTime)
	}
	if value, ok := _u.mutation.UsageResetMonthly(); ok {
		_spec.SetField(apikey.FieldUsageResetMonthly, field.TypeTime, value)
	}
	if _u.mutation.UsageResetMonthlyCleared() {
		_spec.ClearField(apikey.FieldUsageResetMonthly, field.TypeTime)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(apikey.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(apikey.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(apikey.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(apikey.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apikey.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.GroupTable,
			Columns: []string{apikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.GroupTable,
			Columns: []string{apikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.UsageLogsTable,
			Columns: []string{apikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.UsageLogsTable,
			Columns: []string{apikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.UsageLogsTable,
			Columns: []string{apikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &APIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
