// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gatewayapp

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/gatewaycore"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/gatewayruntime"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"sync"
)

// Injectors from wire.go:

func initializeApplication() (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	groupRepository := repository.NewGroupRepository(client, db)
	redisClient := repository.ProvideRedis(configConfig)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig)
	settingRepository := repository.NewSettingRepository(client)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	proxyRepository := repository.NewProxyRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator)
	identityCache := repository.NewIdentityCache(redisClient)
	identityService := service.NewIdentityService(identityCache)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, oAuthRefreshAPI)
	sessionLimitCache := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	digestSessionStore := service.NewDigestSessionStore()
	gatewayService := provideTechnicalGatewayService(accountRepository, groupRepository, usageLogRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, rateLimitService, identityService, httpUpstream, deferredService, claudeTokenProvider, sessionLimitCache, rpmCache, settingService, tlsFingerprintProfileService, digestSessionStore)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	privacyClientFactory := providePrivacyClientFactory()
	openAIOAuthService := service.ProvideOpenAIOAuthService(proxyRepository, openAIOAuthClient, privacyClientFactory)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	openAIGatewayService := provideTechnicalOpenAIGatewayService(accountRepository, usageLogRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, rateLimitService, httpUpstream, deferredService, openAITokenProvider, settingService)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	internal500CounterCache := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, internal500CounterCache)
	geminiMessagesCompatService := service.NewGeminiMessagesCompatService(accountRepository, groupRepository, gatewayCache, schedulerSnapshotService, geminiTokenProvider, rateLimitService, httpUpstream, antigravityGatewayService, configConfig)
	runtime, err := gatewayruntime.NewRuntime(groupRepository, gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, configConfig)
	if err != nil {
		return nil, err
	}
	v := provideCleanup(runtime, client, redisClient, schedulerSnapshotService, openAIGatewayService, deferredService, timingWheelService)
	application := &Application{
		Runtime: runtime,
		Cleanup: v,
	}
	return application, nil
}

// wire.go:

// Application owns the in-process account gateway and the infrastructure it
// opened. The caller remains responsible for user authentication and billing.
type Application struct {
	Runtime gatewaycore.Runtime
	Cleanup func()
}

// Open loads the Next API technical account gateway from its normal config,
// database, and Redis settings. No HTTP listener is created.
func Open() (*Application, error) {
	return initializeApplication()
}

func providePrivacyClientFactory() service.PrivacyClientFactory {
	return repository.CreatePrivacyReqClient
}

func provideCleanup(
	runtime gatewaycore.Runtime,
	client *ent.Client,
	rdb *redis.Client,
	schedulerSnapshot *service.SchedulerSnapshotService,
	openAIGateway *service.OpenAIGatewayService,
	deferred *service.DeferredService,
	timingWheel *service.TimingWheelService,
) func() {
	var once sync.Once
	return func() {
		once.Do(func() {
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			if runtime != nil {
				_ = runtime.Close(ctx)
			}
			if openAIGateway != nil {
				openAIGateway.CloseOpenAIWSPool()
			}
			if schedulerSnapshot != nil {
				schedulerSnapshot.Stop()
			}
			if deferred != nil {
				deferred.Stop()
			}
			if timingWheel != nil {
				timingWheel.Stop()
			}
			if rdb != nil {
				_ = rdb.Close()
			}
			if client != nil {
				_ = client.Close()
			}
		})
	}
}
